import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'registration',
    'running-tests',
    'credentials',
    {
      type: 'category',
      label: 'Playbooks',
      link: {
        type: 'doc',
        id: 'playbooks/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'playbooks/categories',
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/local-kind',
        'operations/e2e-noetl-dev',
      ],
    },
  ],
};

export default sidebars;
